<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company [
    <!ELEMENT company (employ, client)*>
    <!ELEMENT employ (name, (email, number)+, password)>
    <!ELEMENT client (name, email, password)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT number (#PCDATA)>
    <!ELEMENT password (#PCDATA)>
    
]>
<company>
    <employ>
        <name>raees</name>
        <email>raees@gmail.com</email>
        <number>03145025</number>
        <password>12345</password>
        <!-- adding the both number & password -->
    </employ>
    
    
    <client>
        <name>sadd</name>
        <email>saad.com</email>
        <password>1234567898</password>
    </client>
</company>
