<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE shope [
    <!ELEMENT shope (books)>
    <!ELEMENT books (id,name,age,number,email)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT number (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
]>
<shope>
    <books>
        <id>101</id>
        <name>raees</name>
        <age>21</age>
        <number>03172133969</number>
        <email>raees@gmail.com</email>
    </books>
    <books>
        <id>101</id>
        <name>raees</name>
        <age>21</age>
        <number>03172133969</number>
        <email>raees@gmail.com</email>
    </books>
</shope>
